### ISSUE TITLE
http 和 ws 推送消息 严重漏消息啊

### ISSUE THREAD

**Issue by WyntersN** [xianrenqh/wrest-chat-gohttp#1]
![image](https://github.com/user-attachments/assets/9dcb2d98-2806-4067-8439-87bd30c343fe)
发了2组 12345
http 和 ws 推送消息 严重漏消息啊

**Comment by xianrenqh** [comment]
![Snipaste_2024-09-07_09-22-08](https://github.com/user-attachments/assets/f1986fc5-3033-44ef-bf3c-1eedec76e3ac)
正常啊 没有漏消息，上图中我是用php启的websocket服务来监听的ws消息

**Comment by xianrenqh** [comment]
另外，我的gohttp服务和ws消息监听是在一台机器上，响应还是比较快的

**Comment by WyntersN** [comment]
为啥我的db3数据库 都没有记录🙉🙉🙉🙉，我为啥总是会漏

**Comment by WyntersN** [comment]
是我的问题 我把推送机制改成了 随机推送一个，我不希望全部都推送，如果我多服务器ws连接
的话他推送的消息，我全部服务器都要去执行了！！！

**Comment by WyntersN** [comment]
那图片下载会超时咋办， @xianrenqh
